### ISSUE TITLE
AttributeError: 'Delegate' object has no attribute '_library'

### ISSUE THREAD

**Issue by mrpajax** [guichristmann/edge-tpu-tiny-yolo#7]
**Python version**
`3.7.8`
**TensorFlow version**
`1.15.0`
**Command**
`py .\inference.py --model .\out_edgetpu.tflite --classes .\plc.names --image 1.jpg --edge_tpu --quant --anchors .\tiny_yolo_anchors.txt`
**Logs**
`2020-07-14 09:41:13.618078: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-07-14 09:41:13.626348: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File ".\inference.py", line 223, in <module>
    interpreter = make_interpreter(args.model, args.edge_tpu)
  File ".\inference.py", line 35, in make_interpreter
    tf.lite.experimental.load_delegate(EDGETPU_SHARED_LIB)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Exception ignored in: <function Delegate.__del__ at 0x000001B4AC7FE5E8>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'`

**Comment by mrpajax** [comment]
**Resolution**
Install linux
